#!/bin/bash

set -e

# install fonts

git clone --depth=1 https://github.com/googlefonts/NunitoSans.git 
mkdir -p /usr/share/fonts/ && cp -r NunitoSans/fonts/ttf/*.ttf /usr/share/fonts/
fc-cache -f -v && fc-list | grep "NunitoSans"
rm -rf NunitoSans
